### ISSUE TITLE
Days improvement

### ISSUE THREAD

**Issue by RatFou** [Harisene/react-native-customizable-countdown#1]
Hey, I've added days implementation in the countdown for one of my projects.

I can't push a new branch on your poject so I've pushed it on mine: https://github.com/RatFou/react-native-customizable-countdown/tree/days

Please let me know if you want me to push on your tree.

**Comment by RatFou** [comment]
@Harisene I think there is some bug on the Branch I pushed :)

**Comment by Harisene** [comment]
Hi @RatFou. Thank you for using  **react-native-customizable-countdown**.  I really appreciate you are trying to add more features into the component. Try to solve the bug and let me know. I'll check that too. Cheers :) :)
